# Generated by Django 6.1.1 on 2026-09-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Match quality 0–100 (see matches.engine for scoring rules).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=10)),
                ('score_category', models.PositiveSmallIntegerField(default=0)),
                ('score_location', models.PositiveSmallIntegerField(default=0)),
                ('score_title', models.PositiveSmallIntegerField(default=0)),
                ('score_description', models.PositiveSmallIntegerField(default=0)),
                ('score_date', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(help_text='Must have item_type=FOUND.', on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='items.item')),
                ('lost_item', models.ForeignKey(help_text='Must have item_type=LOST.', on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='items.item')),
            ],
            options={
                'verbose_name': 'Item Match',
                'verbose_name_plural': 'Item Matches',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
