# Generated by Django 6.1.1 on 2026-09-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim Submitted'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('CLAIM_WITHDRAWN', 'Claim Withdrawn'), ('ITEM_ARCHIVED', 'Item Archived'), ('ITEM_RESTORED', 'Item Restored'), ('POSSIBLE_MATCH', 'Possible Match Found'), ('MATCH_CONFIRMED', 'Match Confirmed'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='claims.claim')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='items.item')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
